name: cfop_na_mao
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  # PACOTE DE SPLASH ADICIONADO AQUI
  


flutter:
  uses-material-design: true

  # PASTA DE ASSETS DECLARADA AQUI
  assets:
    - assets/

